server:
  port: 7002

eureka:
  instance:
    hostname: eureka7002.com  #服务端实例名称
  client:
    #false表示不再向服务中心注册自己
    register-with-eureka: false
    #false表示自己就是注册中心，职责是维护注册实例，无需检索服务
    fetch-registry: false
    #设置与Eureka交互的地址查询服务和注册服务都要依赖这个地址
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/