server:
  port: 8001

spring:
  application:
    name: cloud-provider-hystrix-payment

eureka:
  client:
    #true表示向服务中心注册自己
    register-with-eureka: true
    #false表示自己就是注册中心，职责是维护注册实例，无需检索服务
    fetch-registry: true
    #设置与Eureka交互的地址查询服务和注册服务都要依赖这个地址
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka