server:
  port: 80

eureka:
  client:
    #true表示向服务中心注册自己
    register-with-eureka: false
    #设置与Eureka交互的地址查询服务和注册服务都要依赖这个地址
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka #集群版


ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000

feign:
  hystrix:
    enabled: true